# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://bitbucket.org/datami/ios-podspec.git'

target 'datami-smisdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for datami-smisdk
  pod 'SmiSdk'

end
